name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute datetime tag (UTC)
        id: vars
        run: echo "TAG=$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            skcha/llm-serve:${{ steps.vars.outputs.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
